name: Continuous Integration

on:
  push:
    paths:
      - src/*
      - .github/*
      - Cargo.toml
  pull_request:
    paths:
      - src/*
      - .github/workflows/*.yml
      - Cargo.toml

defaults:
  run:
    shell: bash

jobs:
  conventional_commits:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.5

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: cargo build

      - name: Test project
        run: cargo test