name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check