name: Linter

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: cargo clippy -- -D warnings